### ISSUE TITLE
The man command does not work

### ISSUE THREAD

**Issue by ghost** [sherpya/android-busybox#2]
On the computer it works, but on the android does not want to work!
`BusyBox v1.25.1-meefik (2016-12-23 11:45:52 MSK) multi-call binary.

Usage: man [-aw] [MANPAGE]...

Format and display manual page

	-a	Display all pages
	-w	Show page locations`
I put the manual in the folder and it does not work.
`root@Lenovo A319:/system # man accessdb
man: no manual entry for 'accessdb'
help!!!!
`
`1|root@Lenovo A319:/system # cat /etc/man.conf                                 
MANDATORY_MANPATH /system/usr/share/man
`
Here it is in the folder
`root@Lenovo A319:/system # ls /system/usr/share/man
accessdb.8.gz`
What should I do???????????????

**Comment by sherpya** [comment]
unfortunately man applet does need nroff (from groff base)

**Comment by ghost** [comment]
Then everything is clear! I'm going to translate the program nroff under the android.

**Comment by MihaiChirculete** [comment]
@garilla22  Try this out: https://github.com/MihaiChirculete/android-man.git
Note that it is a work in progress therefore at the moment there are only a few man pages added.
