### ISSUE TITLE
Final linking fails with message "internal error in do_print_to_mapfile"

### ISSUE THREAD

**Issue by harish2704** [sherpya/android-busybox#3]
Final linking of busyboxy_stripped fails with message 
```
arm-linux-androideabi/bin/ld: internal error in do_print_to_mapfile, at /s/ndk-toolchain/src/build/../binutils/binutils-2.25/gold/output.h:395
```

After googling, from this page ( http://lists.busybox.net/pipermail/busybox-cvs/2015-September/035246.html ) I found that,  we have to use an additional option `-fuse-ld=bfd
` while doing linking.

When I tried that, it got resolved.

**Comment by sherpya** [comment]
perhaps is a binutils bug :D

**Comment by sherpya** [comment]
just used the latest ndk and it builds fine (r17b) re-open if you get problems
