### ISSUE TITLE
busybox Android

### ISSUE THREAD

**Issue by AhmedX6** [sherpya/android-busybox#6]
Hello,

I would like to compile a busybox for android.

But I don't find an Android.mk available on your repo.

I tried with other repos but I have so many errors on compilation. Could you help me please ?

Thanks

**Comment by sherpya** [comment]
Hi, it's supposed to be compiled with android ndk standalone toolchain, read ANDROID.md

**Comment by AhmedX6** [comment]
Yes sorry but I mean build it on AOSP device tree.

Is it possible ?

**Comment by sherpya** [comment]
lineageos should already have a buildable busybox
